### ISSUE TITLE
game events

### ISSUE THREAD

**Issue by thmsndk** [adventureland-community/typed-adventureland#6]
`game.on` has a lot of different events one can listen to. some of them are detailed here http://adventure.land/docs/code/game/events

As a minimum we should type theese events specifically, but if there are others, they should also be typed.

**Comment by Telokis** [comment]
Many events have been handled in https://github.com/adventureland-community/typed-adventureland/blob/dev/src/game-event.ts#L157.

I would suggest we close this issue and create more precise ones in the future when the need arise.
