### ISSUE TITLE
character events

### ISSUE THREAD

**Issue by thmsndk** [adventureland-community/typed-adventureland#7]
`character.on` allows you to listen to character specific events. some of the mare documented here http://adventure.land/docs/code/character/events

As a minimum those should be typed, but any undocumented events should also be typed.

**Comment by Telokis** [comment]
Since the release have been made public, we've added a lot of events in https://github.com/adventureland-community/typed-adventureland/blob/dev/src/character-event.ts#L180.

I would suggest we close this issue so we can create more precise ones when problems arise in the future.
